const mongoose = require("mongoose");

/**
 * An in-app message addressed to one person.
 *
 * Finget has had no notification channel until now — Milestone 3 wanted to tell
 * a group its Wrapped was ready and had nowhere to put the message. This is
 * that missing channel, kept deliberately small: a kind, a body, an optional
 * link, and a read flag. It is not an activity feed (the group already has one)
 * and it is not an event log.
 *
 * Everything here is generated by Finget about the reader's own money. Nothing
 * in it leaves the device to a third party, which is the same promise the rest
 * of the product makes.
 */
const notificationSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },

  kind: {
    type: String,
    enum: ["reminder", "settlement", "wrapped", "system"],
    required: true,
  },

  title: { type: String, required: true },
  body: { type: String, required: true },

  /** Where tapping it should land, as an app-relative path. */
  href: String,

  /** Context for the surface that renders it. Never contains another user's income. */
  groupId: { type: mongoose.Schema.Types.ObjectId, ref: "Group" },
  amountPaise: { type: Number, min: 0 },

  /**
   * A `upi://pay` intent, when the creditor has published a handle. Stored
   * rather than rebuilt so the button keeps working exactly as it was sent.
   * Finget does not process this payment; the link hands off to the reader's
   * own UPI app and the settlement is recorded here only after confirmation.
   */
  payIntent: String,

  readAt: Date,
  createdAt: { type: Date, default: Date.now },
});

/** The unread-badge query, and the list query, are both this index. */
notificationSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model("Notification", notificationSchema);
